# Fly.io app config for Jur-iA backend
# After creating the app with `fly launch`, Fly will fill in the app name.
app = ""
primary_region = "gru"

[build]
  # Uses Dockerfile in repo root

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
